name: Integration tests

on: [push]

jobs:
  integration-test:

    runs-on: ubuntu-latest

    services:
      arango1:
        image: arangodb:3.10.4
        env:
          ARANGO_NO_AUTH: "1"
        ports:
        - 8529:8529
      arango2:
        image: arangodb:3.10.4
        env:
          ARANGO_ROOT_PASSWORD: password
        ports:
        - 8530:8529

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...
